### ISSUE TITLE
[LinkedIn] Only the organization scores shows and disappears

### ISSUE THREAD

**Issue by Marcelo2691** [teamlyzer/chrome-addon#65]
First of all, this extension is soooooo helpful we all needed it without knowing!
On "it jobs" works just perfect but I noticed on LinkedIn on companies that teamlyzer does have data only the score shows and disappears, shows and disappears again nothing else. On other companies works fine.
Thank you for developing such a tool I've already shared it

**Comment by shizpi** [comment]
@Marcelo2691 Would you be able to provide some printscreen or video?
Does it happen in every page and company or just in some cases?

The issue is probably somewhere in https://github.com/teamlyzer/chrome-addon/blob/master/chrome/extension/page/injectors/LandingJobs.js 
Quite usual for selectors in LinkedIn to change so we might have to update this from time to time 😞

**Comment by Marcelo2691** [comment]
Yeah sure!
so to sum it up: 1 second image 1, one second image 2 looping and its not just 1 organization... I' not sure what it is since on others it works just fine 
![1](https://user-images.githubusercontent.com/46998919/109986957-1e7d5600-7cfe-11eb-89ff-e9814444034a.PNG)
![2](https://user-images.githubusercontent.com/46998919/109986960-1f15ec80-7cfe-11eb-923d-be8d15b4ab5c.PNG)

**Comment by shizpi** [comment]
Great, that helps a lot already.

So, I guess it's related with #66.

We need a MutationObserver to check changes in the page and remove/add componentes whenever it changes. This is done like that in LinkedIn and Landing.jobs because they're SPA's.

If all the components don't get injected successfully we try again, and again, again... It seems that this has a missing container to add the salary prediction, so it keeps rerunning and trying to inject it.

Will try to fix it asap, but if you have time you can give it a try running the extension locally in dev mode.

**Comment by Marcelo2691** [comment]
Yeah, no problem!

**Comment by shizpi** [comment]
I will reopen until this is fixed.
